apiVersion: apps/v1
kind: Deployment
metadata:
  name: webservice2-deployment
  labels:
    app: webservice2
spec:
  replicas: 5
  selector:
    matchLabels:
      app: webservice2
  template:
    metadata:
      labels:
        app: webservice2
    spec:
      containers:
      - name: webservice2
        image: localhost:5000/webservice2:2.0
        ports:
        - name: http
          containerPort: 80

        